version: "3"
services:
    object-recognition:
        build: ./src
        ports:
            - 80:80
        environment:
            - "CONFIG_DIR=${CONFIG_DIR}"
            - "ARTIFACT_DIR=${ARTIFACT_DIR}"
        volumes: 
            - "/Users/martin/projects/object_detection/artifacts/config/:${CONFIG_DIR}"
            - "/Users/martin/projects/object_detection/artifacts/outputs/:${ARTIFACT_DIR}"
            - /Users/martin/projects/object_detection/src:/src/
        # stdin_open: true # docker run -i
        # tty: true        # docker run -t
        command: /start-reload.sh
            