version: "3"
services:
    object-recognition:
        build: ./src
        ports:
            - 80:80
        environment:
            - "CONFIG_DIR=${CONFIG_DIR}"
            - "ARTIFACT_DIR=${ARTIFACT_DIR}"
            - "OUTPUT_DIR=${OUTPUT_DIR}"
            - "HOST_CONFIGS=${HOST_CONFIGS}"
        volumes: 
            - "${HOST_CONFIGS}:${CONFIG_DIR}"
            - "${OUTPUT_DIR}:${ARTIFACT_DIR}"
            - "${PWD}/src:/src/"
        # stdin_open: true # docker run -i
        # tty: true        # docker run -t
        command: /start-reload.sh
            